#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-gc-soname1
Version  : 7.6.0
Release  : 12
URL      : https://github.com/ivmai/bdwgc/archive/gc7_6_0.tar.gz
Source0  : https://github.com/ivmai/bdwgc/archive/gc7_6_0.tar.gz
Summary  : A garbage collector for C and C++
Group    : Development/Tools
License  : BSD-2-Clause
Requires: compat-gc-soname1-lib
Requires: compat-gc-soname1-data
BuildRequires : cmake
BuildRequires : libatomic_ops-dev
BuildRequires : pkgconfig(atomic_ops)

%description
gc.def should probably be removed completely.
I removed an apparently erroneous line for GC_CreateThread.  Unfortunately
gc.def is referenced in various other places I cannot easily edit.  -HB

%package data
Summary: data components for the compat-gc-soname1 package.
Group: Data

%description data
data components for the compat-gc-soname1 package.


%package dev
Summary: dev components for the compat-gc-soname1 package.
Group: Development
Requires: compat-gc-soname1-lib
Requires: compat-gc-soname1-data
Provides: compat-gc-soname1-devel

%description dev
dev components for the compat-gc-soname1 package.


%package lib
Summary: lib components for the compat-gc-soname1 package.
Group: Libraries
Requires: compat-gc-soname1-data

%description lib
lib components for the compat-gc-soname1 package.


%prep
%setup -q -n bdwgc-gc7_6_0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1514300450
%autogen --disable-static --enable-cplusplus
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1514300450
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
%exclude /usr/share/gc/AUTHORS
%exclude /usr/share/gc/README.DGUX386
%exclude /usr/share/gc/README.Mac
%exclude /usr/share/gc/README.OS2
%exclude /usr/share/gc/README.amiga
%exclude /usr/share/gc/README.arm.cross
%exclude /usr/share/gc/README.autoconf
%exclude /usr/share/gc/README.cmake
%exclude /usr/share/gc/README.cords
%exclude /usr/share/gc/README.darwin
%exclude /usr/share/gc/README.environment
%exclude /usr/share/gc/README.ews4800
%exclude /usr/share/gc/README.hp
%exclude /usr/share/gc/README.linux
%exclude /usr/share/gc/README.macros
%exclude /usr/share/gc/README.md
%exclude /usr/share/gc/README.rs6000
%exclude /usr/share/gc/README.sgi
%exclude /usr/share/gc/README.solaris2
%exclude /usr/share/gc/README.symbian
%exclude /usr/share/gc/README.uts
%exclude /usr/share/gc/README.win32
%exclude /usr/share/gc/README.win64
%exclude /usr/share/gc/debugging.html
%exclude /usr/share/gc/finalization.html
%exclude /usr/share/gc/gc.man
%exclude /usr/share/gc/gcdescr.html
%exclude /usr/share/gc/gcinterface.html
%exclude /usr/share/gc/leak.html
%exclude /usr/share/gc/overview.html
%exclude /usr/share/gc/porting.html
%exclude /usr/share/gc/scale.html
%exclude /usr/share/gc/simple_example.html
%exclude /usr/share/gc/tree.html

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/gc.h
%exclude /usr/include/gc/cord.h
%exclude /usr/include/gc/cord_pos.h
%exclude /usr/include/gc/ec.h
%exclude /usr/include/gc/gc.h
%exclude /usr/include/gc/gc_allocator.h
%exclude /usr/include/gc/gc_backptr.h
%exclude /usr/include/gc/gc_config_macros.h
%exclude /usr/include/gc/gc_cpp.h
%exclude /usr/include/gc/gc_disclaim.h
%exclude /usr/include/gc/gc_gcj.h
%exclude /usr/include/gc/gc_inline.h
%exclude /usr/include/gc/gc_mark.h
%exclude /usr/include/gc/gc_pthread_redirects.h
%exclude /usr/include/gc/gc_tiny_fl.h
%exclude /usr/include/gc/gc_typed.h
%exclude /usr/include/gc/gc_version.h
%exclude /usr/include/gc/javaxfc.h
%exclude /usr/include/gc/leak_detector.h
%exclude /usr/include/gc/weakpointer.h
%exclude /usr/include/gc_cpp.h
%exclude /usr/lib64/libcord.so
%exclude /usr/lib64/libgc.so
%exclude /usr/lib64/libgccpp.so
%exclude /usr/lib64/pkgconfig/bdw-gc.pc

%files lib
%defattr(-,root,root,-)
%exclude /usr/lib64/libcord.so.1
%exclude /usr/lib64/libcord.so.1.0.3
%exclude /usr/lib64/libgccpp.so.1
%exclude /usr/lib64/libgccpp.so.1.0.3
/usr/lib64/libgc.so.1
/usr/lib64/libgc.so.1.0.3
